baseURL = "https://ratnakar.ml/"
languageCode = "en-us"
title = "Ratnakar Muramalla"
theme = "hugo-resume"

[params]
    firstName = "Ratnakar"
    lastName = "Muramalla"
    address = "Banglore, India"
    phone = "+919014345254"
    contactNote = " Full Stack Developer"
    profileImage = "img/Ratnakar.png"
    email = "fullstackwebdeveloper@gmail.com"
    description = "Software Platform Engineer with experience leveraging agile, DevOps, and CI/CD to manage large scale distributed platforms both on prem and in public cloud."
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = true
    showPublications = true
    showExperience = true
    showEducation = true

    showQr = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/edwardwebb/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/ratnakarm/"

[[params.handles]]
    name = "Bitbucket"
    link = "https://bitbucket.org/eddiewebb/"

[[params.handles]]
    name = "Stack Overflow"
    link = "https://stackoverflow.com/users/story/82880"
    icon = "stack-overflow"

[[params.handles]]
    name = "Keybase"
    link = "https://keybase.io/edwardawebb"
    icon = "keybase"

[params.google.analytics]
    trackerID = ""
